name: Go API Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go Test
        uses: peter-evans/workflow-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: calebtraceyco/devops
          workflow: test.yml
          ref: main
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go Lint
        uses: peter-evans/workflow-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: calebtraceyco/devops
          workflow: lint.yml
          ref: main
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Analyze Code
        uses: peter-evans/workflow-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: calebtraceyco/devops
          workflow: codeql.yml
          ref: main
  # BUILD STAGE
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build Image
        uses: peter-evans/workflow-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: calebtraceyco/devops
          workflow: build.yml
          ref: main
        needs: [ test, lint, analyze ]
  # PUSH IMAGE STAGE
  push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Push Image
        uses: peter-evans/workflow-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: calebtraceyco/devops
          workflow: push.yml
          ref: main
        needs: build
