name: MYB-API CI Pipeline
on:
  workflow_run:
    workflows:
      - "goAPI.yml"
    branches:
      - main
    types:
      - completed
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  import:
    runs-on: ubuntu-latest
    uses: calebtraceyco/devops/.github/workflows/goAPI.yml@v1
