name: MYB-API CI Pipeline
on:
  workflow_run:
    workflows:
      - "goAPI.yml"
    branches:
      - main
    types:
      - completed
jobs:
  checkout:
    runs-on: ubuntu-latest
    uses: actions/checkout@v3
  workflow:
    runs-on: ubuntu-latest
    uses: calebtraceyco/devops/.github/workflows/goAPI.yml@main
