name: MYB-API CI Pipeline
on:
  workflow_run:
    workflows:
      - "goAPI.yml"
    branches:
      - main
    types:
      - completed
jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Go API Workflow
        uses: calebtraceyco/devops/.github/workflows/goAPI@v1
