on:
  # workflow only runs for MYB-XXX merging into main
  push:
    branches:
      - MYB-*
      - main
  pull_request:
    branches:
      - main
      - MYB-*
    types: [ opened, synchronize ]

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          cache: false
      - uses: actions/checkout@v3
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
      - name: Analyze Code
        uses: github/codeql-action/analyze@v2
        with:
          languages: go
          queries: codeql-go
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag myb-api:$(date +%s)
    needs: [ test, lint, analyze ]
  push-image:
    name: Docker Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag myb-api:$(date +%s)
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: calebtracey/myb-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    needs: [ build-image ]
