on:
  push:
    branches:
      - MYB-*
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    strategy:
      matrix:
        go-version: [ 1.20.x ]
        os: [ ubuntu-latest ]
    name: Go Test (Go ${{ matrix.go-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          cache: false
      - uses: actions/checkout@v3
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
        with:
          languages: go
      - name: Analyze Code
        uses: github/codeql-action/analyze@v2
        with:
          repository: ${{ github.repository }}
          languages: go
          queries: codeql-go
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
#        run: docker build . --file Dockerfile --tag myb-api:$(date +%s)
    needs: [ tests, lint, analyze ]
  push-image:
    name: Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Tag Image
        run: |
          docker build -t myb-api .
          docker tag myb-api ghcr.io/${{ github.repository }}:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
#        run: docker push ghcr.io/my-org/my-image:latest
        run: docker push ghcr.io/${{ github.repository }}:latest
    needs: [ build-image ]
