on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
env:
  default-branch: main
  go-versions: 1.16, 1.17
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: latest
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
#        with:
#          token: ${{ secrets.PAT }}
#          repository: calebtraceyco/devops
#          workflow: test.yml
#          ref: main
  lint-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - uses: github/codeql-action/analyze@v2
        with:
          languages: go
          queries: codeql-go
  # BUILD STAGE
#  build:
#    runs-on: ubuntu-latest
#    steps:
##      - name: checkout
#      - uses: actions/checkout@v3
##      - name: Build Image
##        uses: peter-evans/workflow-dispatch@v2
#        with:
#          token: ${{ secrets.PAT }}
#          repository: calebtraceyco/devops
#          workflow: build.yml
#          ref: main
#    needs: [ test, lint, analyze ]
  # PUSH IMAGE STAGE
  push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PUSHING IMAGE..."
#      - name: checkout
#        uses: actions/checkout@v3

    needs: [ test, lint, analyze ]
